version: "3.8"

services: 
  core:
    container_name: mlops_basics_development_core
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - development.env
    build: 
      context: ../../
      dockerfile: environments/development/Dockerfile-core
      shm_size: 12G
      args:
        PYTHON_VERSION: 3.9
        APPLICATION_DIRECTORY: /mlops_basics
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    user: 1000:1000
    volumes:
      - ../../../mlops_basics:/mlops_basics
 
  app:
    container_name: mlops_basics_development_app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build: 
      context: ../../
      dockerfile: environments/development/Dockerfile-app
      shm_size: 12G
      args:
        PYTHON_VERSION: 3.9
        APPLICATION_DIRECTORY: /mlops_basics
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    user: 1000:1000
    volumes:
      - ../../../mlops_basics:/mlops_basics