defaults:
  - data: cola
  - tokenizer: bert
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

onnx_model_path: models/model.onnx
sentence: "The boy is sitting on a bench"
batch_size: 64