defaults:
  - data: cola
  - encoder: bert
  - optimizer: adam
  - tokenizer: bert
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

deterministic: false
batch_size: 64
max_epochs: 1
log_every_n_steps: 10
limit_train_batches: 0.25
limit_val_batches: ${limit_train_batches}