FROM nvidia/cuda:11.0-devel-ubuntu20.04

ARG PYTHON_VERSION
ARG APPLICATION_DIRECTORY
ARG USER_NAME=default

# Restrict python log 
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONPATH ${APPLICATION_DIRECTORY}

# Following is needed to install python 3.9
# RUN apt update && apt install --no-install-recommends -y software-properties-common 
# RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt update && apt install --no-install-recommends -y \
    git curl ssh openssh-client \
    python${PYTHON_VERSION} python3-pip python-is-python3
    
# Following is needed to swtich default python3 version
# For detail, please check following link
# https://unix.stackexchange.com/questions/410579/change-the-python3-default-version-in-ubuntu
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 \
    && update-alternatives --set python3 /usr/bin/python${PYTHON_VERSION} \
    && pip3 install poetry

# Add user. Without this, following process is executed as admin (This will lead file permission problem.). 
RUN useradd -ms /bin/sh ${USER_NAME}
USER ${USER_NAME}
EXPOSE 8000

COPY --chown=${USER_NAME}:${USER_NAME} . ${APPLICATION_DIRECTORY}/

WORKDIR ${APPLICATION_DIRECTORY}
RUN poetry install --no-dev && rm -rf /home/python/.cache/pip

# Init dvc
RUN dvc init --no-scm
# Configuring remote server in dvc
RUN dvc remote add -d storage ${GDRIVE_ID}
RUN dvc remote modify storage gdrive_use_service_account true
RUN dvc remote modify storage gdrive_service_account_json_file_path ${GDRIVE_CREDS_PATH}

# Pulling the trained model
RUN dvc pull dvcfiles/trained_model.dvc