version: "3.8"

services: 
  core:
    container_name: mlops_basics_continuous_integration_core
    build: 
      context: ../../
      dockerfile: environments/development/Dockerfile-core
      shm_size: 12G
      args:
        PYTHON_VERSION: 3.9
        APPLICATION_DIRECTORY: /mlops_basics
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    user: 1000:1000
    volumes:
      - ../../../MlopsBasics:/mlops_basics