version: "3.8"

services: 
  app:
    container_name: mlops_basics_production_app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build: 
      context: ../../
      dockerfile: environments/production/Dockerfile-app
      shm_size: 12G
      args:
        PYTHON_VERSION: 3.9
        APPLICATION_DIRECTORY: /mlops_basics
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    user: 1000:1000
    command: poetry run uvicorn 'src.app.wsgi:main' --host 0.0.0.0 --port 8000
